# .github/workflows/main.yml
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install NPM dependencies
        run: npm install

      - name: Install dependencies
        run: npm ci

      - name: Serverless AWS authentication
        run: npx serverless --component=serverless-next config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}

      # name: Download `.serverless` state from S3
      #  run: aws s3 sync .serverless s3://clink-homepage-serverless-state-bucket/cauclink.com/staging/.serverless --delete
    
      - name: Deploy to AWS
        run: npx serverless

      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://clink-homepage-serverless-state-bucket/cauclink.com/staging/.serverless --delete